### ISSUE TITLE
Import all other addons from the wiki

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/wiki-addon#1]
There is a scripting hello world tutorial, and a 3D items pack: https://github.com/Bedrock-OSS/bedrock-wiki/tree/gh-pages/assets/packs

There is also https://wiki.bedrock.dev/assets/packs/tutorials/custom-item-models/CustomItemModels_attachable.mcaddon

Please put each, unzipped, into its own folder.

**Comment by Dreamedc2015** [comment]
i believe ive done this and ill close the issue
